pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    environment {
        workDir = 'example/maven'
    }

    stages {
        stage('Build') {
            dir("${workDir}") {
                steps {
                    sh 'mvn -B clean package'
                }
            }
        }

        stage('静的コード解析') {
            dir("${workDir}") {
                steps {
                    parallel(
                        '静的コード解析' : {
                            step([
                                $class: 'CheckStylePublisher',
                                pattern: "checkstyle/*.xml"
                            ])
                            step([
                                $class: 'FindBugsPublisher',
                                pattern: "findbugs/*.xml"
                            ])
                            step([
                                $class: 'PmdPublisher',
                                pattern: "pmd/*.xml"
                            ])
                            step([
                                $class: 'DryPublisher',
                                pattern: "cpd/*.xml"
                            ])
                            step([
                                $class: 'WarningsPublisher',
                                consoleParsers: [
                                    [parserName: 'Java Compiler (javac)'],
                                    [parserName: 'Maven'],
                                ]
                            ])
                        },
                        'ステップカウント': {
                            stepcounter settings: [
                                [key:'Java', filePattern: "src/main/java/**/*.java"]
                            ]
                        },
                        'タスクスキャン': {
                            step([
                                $class: 'TasksPublisher',
                                pattern: './**',
                                ignoreCase: true,
                                high: 'System.out.System.err',
                                normal: 'TODO,FIXME,XXX',
                            ])
                        }
                    )
                }
            }
        }


        stage('テスト') {
            dir("${workDir}") {
                steps {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archive 'target/*.jar'
                    step([
                        $class: 'JacocoPublisher',
                        execPattern: "*.exec",
                        exclusionPattern: '**/*Test.class'
                    ])
                }
            }
        }
    }
}